### ISSUE TITLE
Blatant oversimplification of indexed images

### ISSUE THREAD

**Issue by Nyerguds** [vanomaisuradze/lock-bitmap#2]
8-bit is not grayscale. This code serves as basis for loads of misunderstandings on that concept.

If you include indexed handling in it, you should support indexed colours properly, with a Get/SetIndex in addition to the Get/SetPixel, and proper exceptions when trying SetPixel on an indexed type or trying the Get/SetIndex on a non-indexed type, and with support for 4-bit and 1-bit.

If not, you should simply remove 8-bit support altogether instead of incorrectly handling indexed as grayscale. There is no real relation in the .Net Bitmap class between grayscale and 8-bit. There's not even standard support for making that; you would have to generate a grayscale fade palette yourself.

**Comment by vano-maisuradze** [comment]
I never mentioned that 8-bit is grayscale, but you are right, it's better to remove 8 bit support.

**Comment by Nyerguds** [comment]
Actually, the comment on 8-bit said "Red, Green and Blue values are the same". Assuming these three are equal indeed means it's a gray colour, and using that value as index only works if the image has a grayscale black to white fade as colour palette. So no, you didn't actually mention it, but the code _did_ assume it.
